---
resources:
  - name: fauna-jvm-repository
    type: git
    icon: github
    source:
      uri: https://github.com/fauna/faunadb-jvm.git
      branch: oss-703

  - name: fauna-jvm-repository-docs
    type: git
    icon: github
    source:
      uri: git@github.com:parkhomenko/faunadb-jvm.git
      branch: gh-pages-test
      private_key: ((fauna/repo.key))

jobs:
  - name: release
    serial: true
    public: false
    plan:
      - get: fauna-jvm-repository
      - get: fauna-jvm-repository-docs

      - task: integration-tests
        file: fauna-jvm-repository/concourse/tasks/integration-tests.yml
        privileged: true
        params:
          FAUNA_ROOT_KEY: ((fauna.secret))
          FAUNA_DOMAIN: ((fauna.domain))
          FAUNA_SCHEME: ((fauna.scheme))
          FAUNA_PORT: ((fauna.port))

      - task: publish
        file: fauna-jvm-repository/concourse/tasks/publish.yml
        params:
          SONATYPE_USER: ((fauna/sonatype.user))
          SONATYPE_PASS: ((fauna/sonatype.password))
          GPG_PRIVATE_KEY: ((fauna/gpg.private-key))
          GPG_PUBLIC_KEY: ((fauna/gpg.public-key))
          GPG_PASSPHRASE: ((fauna/gpg.passphrase))
          GPG_SIGNING_KEY: ((fauna/gpg.signing-key))

      - task: publish-docs
        file: fauna-jvm-repository/concourse/tasks/publish-docs.yml

      - put: fauna-jvm-repository-docs
        params:
          repository: fauna-jvm-repository-updated-docs
